# Generated by Django 6.0.6 on 2026-07-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('species', models.CharField(blank=True, choices=[('Dairy', 'Dairy'), ('Beef', 'Beef'), ('Sheep', 'Sheep'), ('Goat', 'Goat'), ('Other', 'Other')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationConcentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClientBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('addresses', models.ManyToManyField(related_name='client_businesses', to='pharmacy.address')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_expiration_date', models.DateField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.address')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('drug_name', models.CharField(max_length=100)),
                ('active_ingredient', models.CharField(max_length=100)),
                ('directions', models.TextField(blank=True, null=True)),
                ('dose', models.CharField(blank=True, max_length=100, null=True)),
                ('milk_withhold_period', models.CharField(blank=True, max_length=100, null=True)),
                ('meat_withhold_period', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_age', models.CharField(blank=True, max_length=100, null=True)),
                ('concentrations', models.ManyToManyField(related_name='medications', to='pharmacy.medicationconcentration')),
                ('sizes', models.ManyToManyField(related_name='medications', to='pharmacy.medicationsize')),
                ('strength_options', models.ManyToManyField(related_name='medications', to='pharmacy.medicationstrength')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.address')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_prescription', models.DateField(help_text='Date of treatment, presciption, or dispensing.')),
                ('quantity', models.PositiveIntegerField()),
                ('animals_treated', models.PositiveIntegerField(help_text='Number of animals treated with this prescription.')),
                ('animal_species', models.CharField(blank=True, max_length=50, null=True)),
                ('dosage_instructions', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, help_text='Duration of treatment (e.g., 5 days, 2 weeks).', max_length=100, null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='Expiration date of the prescription.', null=True)),
                ('route_of_administration', models.CharField(blank=True, help_text='Route of administration (e.g., oral, injection).', max_length=100, null=True)),
                ('number_of_refills', models.PositiveIntegerField(default=0, help_text='Number of refills allowed for this prescription.')),
                ('cautionary_notes', models.TextField(blank=True, help_text='Any cautionary notes or warnings related to the prescription.', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.client')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.doctor')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medication')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.practice')),
                ('strength', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicationstrength')),
            ],
        ),
    ]
