# Generated by Django 6.0.6 on 2026-07-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_historicalmedication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='concentrations',
            field=models.ManyToManyField(blank=True, related_name='medications', to='pharmacy.medicationconcentration'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='medications', to='pharmacy.medicationsize'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='strength_options',
            field=models.ManyToManyField(blank=True, related_name='medications', to='pharmacy.medicationstrength'),
        ),
    ]
