# Generated by Django 6.0.6 on 2026-07-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_medication_concentrations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['brand_name']},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-date_of_prescription', '-created_at']},
        ),
    ]
