# Generated by Django 6.0.6 on 2026-07-18 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_client_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbusiness',
            name='addresses',
        ),
        migrations.AddField(
            model_name='clientbusiness',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_businesses', to='pharmacy.address'),
        ),
        migrations.AddField(
            model_name='clientbusiness',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='pharmacy.client'),
            preserve_default=False,
        ),
    ]
