# Generated by Django 6.0.6 on 2026-07-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_practiceinvite'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clientbusiness',
            constraint=models.UniqueConstraint(fields=('client', 'address'), name='unique_client_business_address'),
        ),
    ]
