# Generated by Django 6.0.6 on 2026-07-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_clientbusiness_unique_client_business_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceinvite',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=10),
        ),
    ]
