# Generated by Django 6.0.6 on 2026-07-18 22:43

from django.db import migrations


def set_creators_as_admin(apps, schema_editor):
    Practice = apps.get_model('pharmacy', 'Practice')
    for practice in Practice.objects.exclude(created_by=None):
        User = practice.created_by.__class__
        User.objects.filter(pk=practice.created_by_id).update(practice_role='admin')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_practiceinvite_role'),
        ('accounts', '0003_user_practice_role'),
    ]

    operations = [
        migrations.RunPython(set_creators_as_admin, noop),
    ]
