# Generated by Django 6.0.6 on 2026-07-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_backfill_practice_creator_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='pharmacy.address'),
        ),
        migrations.AddField(
            model_name='client',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='default_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_practices', to='pharmacy.doctor'),
        ),
        migrations.AlterField(
            model_name='historicalprescription',
            name='animals_treated',
            field=models.PositiveIntegerField(blank=True, help_text='Number of animals treated with this prescription.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalprescription',
            name='duration',
            field=models.CharField(blank=True, help_text='How long to give this medication (e.g., 5 days, 2 weeks) — not the withdrawal period, which is set on the medication itself.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='animals_treated',
            field=models.PositiveIntegerField(blank=True, help_text='Number of animals treated with this prescription.', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, help_text='How long to give this medication (e.g., 5 days, 2 weeks) — not the withdrawal period, which is set on the medication itself.', max_length=100, null=True),
        ),
    ]
