# Generated by Django 6.0.6 on 2026-08-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_client_address_client_business_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['drug_name']},
        ),
        migrations.AlterField(
            model_name='historicalprescription',
            name='duration',
            field=models.CharField(blank=True, help_text='How long to give this medication (e.g., 5 days, 2 weeks).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, help_text='How long to give this medication (e.g., 5 days, 2 weeks).', max_length=100, null=True),
        ),
    ]
