# Generated by Django 6.0.6 on 2026-08-06 18:35

import django.db.models.deletion
from django.db import migrations, models


def copy_business_name_to_client_business(apps, schema_editor):
    '''Clients previously had a single free-text business_name field; move
    any non-blank values into a proper ClientBusiness row (with the
    client's existing address, if any) before the column is dropped.'''
    Client = apps.get_model('pharmacy', 'Client')
    ClientBusiness = apps.get_model('pharmacy', 'ClientBusiness')
    for client in Client.objects.exclude(business_name__isnull=True).exclude(business_name__exact=''):
        ClientBusiness.objects.get_or_create(
            client=client, name=client.business_name.strip(),
            defaults={'address_id': client.address_id},
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_alter_medication_options_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_business_name_to_client_business, noop),
        migrations.RemoveField(
            model_name='client',
            name='business_name',
        ),
        migrations.AddField(
            model_name='historicalprescription',
            name='client_business',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Which of the client's business locations this prescription is for, if any.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pharmacy.clientbusiness'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='client_business',
            field=models.ForeignKey(blank=True, help_text="Which of the client's business locations this prescription is for, if any.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='pharmacy.clientbusiness'),
        ),
    ]
