# Generated by Django 6.0.6 on 2026-08-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_remove_client_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprescription',
            name='prescription_label',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_label',
        ),
    ]
