# Generated by Django 6.0.6 on 2026-07-18 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pharmacy', '0007_practiceinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='pharmacy.practice'),
        ),
    ]
