# Generated by Django 6.0.6 on 2026-07-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='practice_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=10),
        ),
    ]
